blackchat/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(FlaskForm):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

blackchat/__init__.py
import os
import uuid
from flask import Flask
from flask import Blueprint
from flask import render_template
from flask_wtf.csrf import CSRFError, CSRFProtect
from flask_socketio import SocketIO
from flask_login import LoginManager
from flask_session import Session


socketio = SocketIO()
csrf = CSRFProtect()
login_manager = LoginManager()
sess = Session()

# custom imports
from blackchat.views import bp as blackchat_bp
from blackchat import events



def create_app():
    """Create an application."""

    app = Flask(__name__)

    SECRET_KEY = str(uuid.uuid4())
    # WTF_CSRF_SESSION_KEY = str(uuid.uuid4())


    app.config.from_object('blackchat.config.DefaultConfig')
    # app.config.from_envvar('BLACKCHAT_SETTINGS')

    if os.environ['ENV'] in ('prod', 'production'):
        app.config.from_object('blackchat.config.ProductionConfig')
    elif os.environ['ENV'] in ('dev', 'development'):
        app.config.from_object('blackchat.config.DevelopmentConfig')
    elif os.environ['ENV'] in ('stage', 'staging'):
        app.config.from_object('blackchat.config.StagingConfig')
    elif os.environ['ENV'] in ('test', 'testing'):
        app.config.from_object('blackchat.config.TestingConfig')
    else:
        app.logger.info('using default config')

    app.logger.info('config: {}'.format(app.debug))
    app.config['SECRET_KEY'] = SECRET_KEY
    # app.config['WTF_CSRF_SESSION_KEY'] = WTF_CSRF_SESSION_KEY
    app.secret_key = SECRET_KEY

    # NOTE: SESSION_TYPE defaults to null which does not work if using flask-session
    app.config['SESSION_TYPE'] = 'filesystem'


    if not app.debug:
        import logging
        from logging.handlers import TimedRotatingFileHandler
        # https://docs.python.org/3.6/library/logging.handlers.html#timedrotatingfilehandler
        file_handler = TimedRotatingFileHandler(os.path.join(app.config['LOG_DIR'], 'blackchat.log'), 'midnight')
        file_handler.setLevel(logging.WARNING)
        file_handler.setFormatter(logging.Formatter('<%(asctime)s> <%(levelname)s> %(message)s'))
        app.logger.addHandler(file_handler)

    @app.context_processor
    def utility_functions():
        def print_in_console(message):
            print(str(message))

        return dict(mdebug=print_in_console)

    app.register_blueprint(blackchat_bp)

    socketio.init_app(app)
    csrf.init_app(app)
    login_manager.init_app(app)
    sess.init_app(app)

    @app.errorhandler(404)
    def not_found(error):
        return render_template('404.html'), 404

    @app.errorhandler(500)
    def not_found(error):
        return render_template('500.html'), 500

    @app.errorhandler(CSRFError)
    def handle_csrf_error(e):
        app.logger.error(e.description)
        return render_template('csrf_error.html', reason=e.description), 400

    return app

blackchat/views.py
from flask import render_template, Blueprint
from flask import session, redirect, url_for, request

from blackchat.forms import LoginForm

bp = Blueprint('blackchat', __name__)


@bp.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        print('------ {0}'.format(request.form))
        
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)


@bp.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if not name or not room:
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)

blackchat/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
    <meta name="description" content="Chat with Curiosity.">
    <meta name="author" content="Curious Cat">
    <title>{% block title %}Chat for curious minds{% endblock %}</title>
    <meta name="keywords" content="flask,reddit,python,reddit-clone,nginx,lucas ou-yang">

    <!-- Bootstrap core CSS -->
    <!-- <link href="css/bootstrap.css" rel="stylesheet"> -->
    <!-- <link rel="icon" href="https://reddit.codelucas.com/static/imgs/favicon.ico" type="image/x-icon"> -->
    {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}

    <!-- Add custom CSS here -->
    <style>
        body {margin-top: 60px;}
    </style>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

    <div class="container">
      <div id="messages-wrap">
        <div id="messages">
          {% for category, msg in get_flashed_messages(with_categories=true) %}
          <div class="flash-{{ category }} alert alert-dismissable alert-{{ category }} flash-banner">
              {{ msg }}</p>
          {% endfor %}
        </div>
      </div>

      <div class="row main-box">
      {% block content %}

      {% endblock %}
      </div>

      <div class="row" class="" id="footer-row">
          <div class="col-lg-12">
          </div>
      </div>

    </div><!-- /.container -->

    <!-- JavaScript -->
    <!-- TODO Fix this -->
    <!-- <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-37131973-4', 'codelucas.com');
      ga('send', 'pageview');
    </script> -->

    <!-- Let's use a CDN -->

    {# NOTE: MathJax self-hosted cdn retired, use alternate hosts as
             explained here: https://www.mathjax.org/cdn-shutting-down/
    #}
    <!-- <script  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script> -->
    <!-- <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?...">
    </script> -->
    <script
      src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    {% block scripts %}


    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      TeX: {
         equationNumbers: {  autoNumber: "AMS"  },
         extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js", "color.js"]
      }
    });
    </script>


    {% endblock %}
  </body>
</html>

blackchat/templates/chat.html
{% extends "base.html" %}

{% block content %}

    <head>
        <title>Black-Chat: {{ room }}</title>
        <!-- <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script> -->
        <!-- <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script> -->

        <script
              src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.slim.js"></script>
        <script type="text/javascript">
            var csrf_token = "{{ csrf_token() }}";
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
        </script>

        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){

                socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + '/chat');

                //socket = io.connect('https://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    console.log(data);
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    console.log(data);
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('blackchat.index') }}";
                });
            }
        </script>
    </head>
    <body>
        <h1>Black-Chat: {{ room }}</h1>
        <form method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
        <textarea id="chat" cols="80" rows="20"></textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>
        <a href="#" onclick="leave_room();">Leave this room</a>
    </body>

{% endblock %}

blackchat/templates/csrf_error.html
{% extends "base.html" %}

{% block content %}
<div class="col-lg-9">
  <h1>400</h1>
  <p class="lead">CSRFError!</p>
</div>
{% endblock %}

blackchat/templates/index.html
<!-- <!DOCTYPE html> -->
{% extends "base.html" %}

{% block content %}
  <body>
      <h1>Black-Chat</h1>
      <form method="POST">
          <!-- {{ form.hidden_tag() }} -->
          {{ form.csrf_token }}
          {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
          {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
          {{ form.submit() }}
      </form>
  </body>
{% endblock %}